### ISSUE TITLE
Release a new version on CPAN to support `new_auth_method`

### ISSUE THREAD

**Issue by scottchiefbaker** [martin8883/MikroTik-API#12]
`new_auth_method`  is needed to connect to any MikroTik device with semi-recent firmware. That configuration option is not available with the currently released version (1.0.5) on CPAN. Please update CPAN with the newest version.

**Comment by martin8883** [comment]
Correct. I will try to do IT during next days.

**Comment by scottchiefbaker** [comment]
Just so it's logged in case other people want to reference it.

[API docs on login method](https://wiki.mikrotik.com/wiki/Manual:API#Initial_login)

**Comment by scottchiefbaker** [comment]
Do you plan on making `new_auth_method` the default moving forward? It's going to be increasingly uncommon for anyone to ever need the old method.

I like the way this [PHP library](https://github.com/BenMenking/routeros-api/blob/master/routeros_api.class.php#L115) implemented the new method. Basically they default to the "new" auth method, and if that fails they fall back to trying the old method. This makes it so the same library and same code can connect to any firmware version.

**Comment by martin8883** [comment]
There is already patch for this behaviour. I will have a deeper look into it and probably integrate it:
https://github.com/martin8883/MikroTik-API/pull/4 at the end.

**Comment by martin8883** [comment]
Has been uploaded as 1.1.0 to CPAN. Will be available within about 2 hours.
