### ISSUE TITLE
Need an option to support both the old and new auth method with the same code base

### ISSUE THREAD

**Issue by scottchiefbaker** [martin8883/MikroTik-API#17]
I have a script that monitors WiFi clients on two different sets of MT equipment. One has been updated to 6.45.x and the other is still on 6.40.x. Because of this discrepancy I can't use the same script to monitor them because they use different authentication schemes.

I propose we implement a login method like this [PHP Library](https://github.com/BenMenking/routeros-api/blob/master/routeros_api.class.php#L109) that tries the new auth method first, and falls back to the old way if it fails. This will allow the module to work for both authentication schemes.

Login API [docs](https://github.com/BenMenking/routeros-api/blob/master/routeros_api.class.php#L109)

**Comment by scottchiefbaker** [comment]
Apologies, I didn't realize you had [already](/martin8883/MikroTik-API/commit/a7e9bba52d15ba7d122cc81a51f042554cf96146) done this. 

Good work!

**Comment by martin8883** [comment]
Nice to know that the fallback works.

**Comment by scottchiefbaker** [comment]
It does indeed work!
