### ISSUE TITLE
Mikrotik API cannot login without password

### ISSUE THREAD

**Issue by yusrideb** [martin8883/MikroTik-API#5]
Best Regards,

I'm having trouble using MikroTik::API.
If the Mikrotik Device does not have a password, cannot execute query and error output :
`
Use of uninitialized value in die at /usr/local/share/perl/5.24.1/MikroTik/API.pm line 232.
`

By default mikrotik does not have a password. It should be able to connect via the API

After editing into `API.pm` on section `BUILD`, Mikrotik can connected. (see d8a9258)

Script to testing : 
```
my $api = MikroTik::API->new({
  host => '192.168.2.2',
  username => 'admin',
  password => '',
  use_ssl => 0,
  port => 8728
});

my ( $ret_get_identity, @aoh_identity ) = $api->query( '/system/identity/print', {}, {} );
print "Name of router: $aoh_identity[0]->{name}\n";

$api->logout();
```

Thanks.

**Comment by martin8883** [comment]
Thank you for pull request. Merged it and added two fixes.

**Comment by yusrideb** [comment]
thanks for your attentions.
